[package]
name = "json-to-sh"
version = "0.1.0"
authors = ["mlvzk <mlvzk@protonmail.com>"]
edition = "2018"

[dependencies]
streaming-iterator = "0.1.4"
lexical = { version = "5.2", features = ["trim_floats"] }
